### ISSUE TITLE
Tried running Nodopoly but just get a blank screen

### ISSUE THREAD

**Issue by wavesailor** [jewkesy/nodopoly#1]
I followed and installed nodopoly according to your instructions but when I run it I get a blank screen with only this following appearing:
# Nodopoly

**Welcome to Nodopoly**

The output from `npm start` is indicated below:

```
Starting game server
Option log level is not valid. Please refer to the README.
Express server listening.  Use http://externalIPAddress:3000
Server is now listening on TCP/IP 192.168.2.111:3366
Connected to 'nodopoly' database
GET / 200 752.245 ms - 391
GET /stylesheets/style.css 200 16.914 ms - 3142
GET /javascripts/jquery-1.11.1.min.js 200 12.797 ms - 95786
GET /javascripts/game.js 200 4.650 ms - 13794
GET / 200 64.210 ms - 391
GET /stylesheets/style.css 200 6.882 ms - 3142
GET /javascripts/game.js 200 2.138 ms - 13794
GET /javascripts/jquery-1.11.1.min.js 200 1.963 ms - 95786
```

**Comment by jewkesy** [comment]
Hello Wavesailor,

I think the default route isn't set properly in the code.  In terms of visuals I only got as far as generating the gameboard which can be seen at http://localhost:3000/gameboard

Sadly I had to park this project since I had other commitments.  My intended approach was to drive the game using nodejs and socket.io to generate chat messages across all connected devices (check out the tabs on the gameboard page).  The messages could come from other users, but would also be used by the application to update all connected sessions.  I would have then stored the game state in MongoDB so users could reconnect and play their turn.

I noticed that you are interested in AngularJS, I've been working on a repo that you might be interested in forking - https://github.com/jewkesy/FormulaOne , this was originally a NodeJS application but I soon converted it to AngularJS as a learning exercise.  I host it on GitHub so that I don't need a dedicated server.  It also integrates with a MongoDB sandbox to cache the content.

Thanks
Daryl

**Comment by wavesailor** [comment]
Hi Daryl,

Thanks for update. Funny thing was that I first found a similar F1 app http://www.toptal.com/angular-js/a-step-by-step-guide-to-your-first-angularjs-app  
... and then found your  nodopoly app. I thought I'd just give it a try .. but am still tinkering around with the F1 app.

Thanks - Grant
